version: '2'
services:

  cassandra:
    image: cassandra
    ports:
    - "9042:9042"
    - "9160:9160"
    volumes:
      - ./cassandra-data:/var/lib/cassandra-data

  kdb:
    image: glens/kdb-ubuntu

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
